# Generated by Django 3.0.7 on 2020-11-26 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be alphanumeric', regex='^[a-zA-Z0-9]*$')])),
                ('PhoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phonenumber', message='Please enter a valid phone number', regex='^[0-9]*$')])),
                ('Password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
